credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: '$2b$12$Lrew0pyKrLOrlvDMIHmjzO8NWdAsyxNmtZn5pM7EVkRH84VH2KcfO' # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: '$2b$12$uzBnqg658SYgtjxEnQwHVuBmnCChawpbbtBhI2UxWug09n./jDB7y' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com